services:
  - type: web
    name: rewear-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: rewear-db
          property: connectionString
      - key: SUPERUSER_SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: web
    name: rewear-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./frontend/dist
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        sync: false

databases:
  - name: rewear-db
    plan: free
    databaseName: rewear
    user: rewear
